---
title: "ttt"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fingertipsR)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(ggjoy)
library(WVPlots)
library(stringr)
library(lattice)
library(kernlab)
library(caret)
library(caretEnsemble)
library(govstyle)
library(viridisLite)
library(viridis)
library(dplyr)
library(psych)
library(GPArotation)
library(data.table)
library(QuantPsyc)
```

```{r}
## Identify suicide profiles
profiles <- profiles()
sui_profiles <- profiles %>%
  filter(str_detect(ProfileName, "[Ss]uicide"))
```

```{r}
## Download profile data
dataset <- fingertips_data(ProfileID = 91,AreaTypeID = 102)
```

```{r}
## Latest data
dataset_latest <- dataset %>%
  group_by(Age, Sex, IndicatorID, Category) %>%
  filter(TimeperiodSortable == max(TimeperiodSortable))
```

```{r}
ds1 <- dataset_latest %>%
  ungroup() %>%
  filter(AreaType == "Counties & UAs (pre Apr 2019)") %>%
  mutate(index = paste(IndicatorName, Age, Sex, sep = "_")) %>%
  dplyr::select(c("AreaName", "index", "Value"))

```

```{r}
## create wide table
analysis <- ds1 %>%
  tidyr::spread(key = index, value = Value)
```

```{r}
## Check NAs
isna <- analysis %>%
  keep(is.numeric) %>%
  map_df(~sum(is.na(.))) %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(-V1)


isna %>%
  filter(V1 > 5) %>%
  arrange(-V1)
```

```{r}
## Exclude variables
isna_filter <- isna %>%
  filter(V1 > 7) %>%
  pull(rowname)
```


```{r}
## remove variables with a lot of missing data
analysis1 <- select_if(analysis, !names(analysis) %in% isna_filter)  
```

```{r}
## exclude areas with no suicide rate in latest data
analysis1 <- analysis1 %>% 
 filter(!is.na(`Years of life lost due to suicide, age-standardised rate 15-74 years: per 10,000 population (3 year average)_15-74 yrs_Persons`
  ))
```

```{r}
## Impute missing data to mean value
analysis1 <- analysis1 %>%
  map_df(function(x) ifelse(is.na(x),  mean(x, na.rm = TRUE), x))
```

```{r}
## rename outcome variable and exclude other suicide variables
analysis1new <- analysis1 %>%
  rename(outcome = `Years of life lost due to suicide, age-standardised rate 15-74 years: per 10,000 population (3 year average)_15-74 yrs_Persons`) %>% 
  dplyr::select( -contains("suicide")) %>%
  rename(Suicide_Rate = 'outcome')
```

```{r}
mean(is.na(analysis1new))

analysis_final_new <- analysis1new %>%
  dplyr::select(-AreaName)

#Move Suicide_Rate column to the first column
analysis_final_new <- analysis_final_new %>% dplyr::select(Suicide_Rate, everything())
```

```{r}
#write.csv(analysis1new,file ="F:/Study/PHE/analysis1new.csv")
#write.csv(analysis_final_new,file ="F:/Study/PHE/analysis_final_new.csv")
```

```{r}
#cor_new <- cor(analysis_final_new) ##correlation matrix
#cor_new
```

```{r}
#Multiple regression model
fmla_new <- Suicide_Rate ~ .

mod_lm_new <- lm(fmla_new, data = analysis_final_new)
#View(mod_lm_new)
summary(mod_lm_new)
lm_tidy_new <- broom::tidy(mod_lm_new) %>%
  filter(p.value < 0.05)
```

```{r}
#Calculate VIF for each variable
lm1 <- lm(analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Female` ~ 
            analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Male`+
            analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Persons`+
            analysis_final_new$`Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons`+
            analysis_final_new$`Children in care_<18 yrs_Persons`+
            analysis_final_new$`Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons`+
            analysis_final_new$`Children in the youth justice system (10-17 yrs)_10-17 yrs_Persons`+
            analysis_final_new$`Children leaving care: rate per 10,000 children aged under 18_<18 yrs_Persons`+
            analysis_final_new$`Depression: Recorded prevalence (aged 18+)_18+ yrs_Persons`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Female`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Male`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Persons`+
            analysis_final_new$`Estimated prevalence of common mental disorders: % of population aged 16 & over_16+ yrs_Persons`+
            analysis_final_new$`Estimated prevalence of common mental disorders: % of population aged 65 & over_65+ yrs_Persons`+
            analysis_final_new$`Estimated prevalence of opiate and/or crack cocaine use_15-64 yrs_Persons`+
            analysis_final_new$`Long-term health problem or disability: % of population_All ages_Persons`+
            analysis_final_new$`Long term claimants of Jobseeker's Allowance_16-64 yrs_Persons`+
            analysis_final_new$`Marital breakup: % of adults_18+ yrs_Persons`+
            analysis_final_new$`Mental Health: QOF prevalence (all ages)_All ages_Persons`+
            analysis_final_new$`Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons`+
            analysis_final_new$`People living alone: % of all usual residents in households occupied by a single person_All ages_Persons`+
            analysis_final_new$`Self-reported wellbeing - people with a high anxiety score_16+ yrs_Persons`+
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18-64 yrs_Persons`+
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18+ yrs_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_65+ yrs_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_All ages_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult social care users who have as much social contact as they would like_18+ yrs_Persons` +
           analysis_final_new$`Successful completion of alcohol treatment_18+ yrs_Persons`+
           analysis_final_new$`Successful completion of drug treatment - non-opiate users_18+ yrs_Persons` +
           analysis_final_new$`Successful completion of drug treatment - opiate users_18+ yrs_Persons` +
           analysis_final_new$`Unemployment (model-based)_16+ yrs_Persons`)
library(car)
vif(lm1)
```

```{r}
lm2 <- lm(analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Female` ~ 
            analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Male`+
            analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Persons`+
            analysis_final_new$`Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons`+
            analysis_final_new$`Children in care_<18 yrs_Persons`+
            analysis_final_new$`Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons`+
            analysis_final_new$`Children in the youth justice system (10-17 yrs)_10-17 yrs_Persons`+
            analysis_final_new$`Children leaving care: rate per 10,000 children aged under 18_<18 yrs_Persons`+
            analysis_final_new$`Depression: Recorded prevalence (aged 18+)_18+ yrs_Persons`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Female`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Male`+
            analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Persons`+
            analysis_final_new$`Estimated prevalence of common mental disorders: % of population aged 16 & over_16+ yrs_Persons`+
            analysis_final_new$`Estimated prevalence of common mental disorders: % of population aged 65 & over_65+ yrs_Persons`+
            analysis_final_new$`Estimated prevalence of opiate and/or crack cocaine use_15-64 yrs_Persons`+
            analysis_final_new$`Long-term health problem or disability: % of population_All ages_Persons`+
            analysis_final_new$`Long term claimants of Jobseeker's Allowance_16-64 yrs_Persons`+
            analysis_final_new$`Marital breakup: % of adults_18+ yrs_Persons`+
            analysis_final_new$`Mental Health: QOF prevalence (all ages)_All ages_Persons`+
            analysis_final_new$`Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons`+
            analysis_final_new$`People living alone: % of all usual residents in households occupied by a single person_All ages_Persons`+
            analysis_final_new$`Self-reported wellbeing - people with a high anxiety score_16+ yrs_Persons`+
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18-64 yrs_Persons`+
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18+ yrs_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_65+ yrs_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_All ages_Persons` +
            analysis_final_new$`Social Isolation: percentage of adult social care users who have as much social contact as they would like_18+ yrs_Persons` +
           analysis_final_new$`Successful completion of alcohol treatment_18+ yrs_Persons`+
           analysis_final_new$`Successful completion of drug treatment - non-opiate users_18+ yrs_Persons` +
           analysis_final_new$`Successful completion of drug treatment - opiate users_18+ yrs_Persons` +
           analysis_final_new$`Unemployment (model-based)_16+ yrs_Persons`)
library(car)
vif(lm2)
```

```{r}
#Sort the multiple linear regression coefficients
MulLinReg_Coef<-mod_lm_new$coefficients
MulLinReg_Coef_df<-as.data.frame(MulLinReg_Coef)
MulLinReg_Coef_Only<-MulLinReg_Coef_df[-1,drop = FALSE,]
sort.MulLinReg_Coef_Only<-MulLinReg_Coef_Only[order(MulLinReg_Coef_Only$MulLinReg_Coef ,decreasing = TRUE), drop = FALSE,]

#write.csv(sort.MulLinReg_Coef_Only,file ="F:/Study/PHE/sort.MulLinReg_Coef_Only.csv")
```

```{r}
#Standardized multiple linear regression and sort the coefficients to see the most importance variable
lm_stan<-lm.beta(mod_lm_new)
lm_stan_df<-as.data.frame(lm_stan)
sort.lm_stan<-lm_stan_df[order(lm_stan_df$lm_stan, decreasing = TRUE), drop=FALSE,]

#write.csv(sort.lm_stan,file ="F:/Study/PHE/sort.lm_stan.csv")
```

```{r}
#Calculate the importance based on coefficients
modvimp_new <- varImp(mod_lm_new, scale = FALSE)
#Sort the biggest importance
sort.modvimp_new<-modvimp_new[order(modvimp_new$Overall,decreasing = TRUE), drop = FALSE,]
#write.csv(sort.modvimp_new,file ="F:/Study/PHE/sort.modvimp_new.csv")
sort.modvimp_new
```

```{r}
#Linear Regression for 'Social Isolation: percentage of adult carers who have as much social contact as they would like_18+ yrs_Persons'
LinReg_1 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_1)
#Plot Linear Regression for Adult carers who have as much social contact as they would like: % of adult carers_18+ yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_18+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_1)
```

```{r}
#Linear Regression for 'Social Isolation: percentage of adult carers who have as much social contact as they would like_All ages_Persons'
LinReg_2 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_All ages_Persons` ,data=analysis_final_new)
summary(LinReg_2)
#Plot Linear Regression for Adult carers who have as much social contact as they would like: % of adult carers_All ages_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult carers who have as much social contact as they would like_All ages_Persons` ,data=analysis_final_new)
abline(LinReg_2)
```

```{r}
#Linear Regression for 'Social Isolation: percentage of adult social care users who have as much social contact as they would like_18+ yrs_Persons'
LinReg_3 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult social care users who have as much social contact as they would like_18+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_3)
#Plot Linear Regression for Adult social care users who have as much social contact as they would like: % of adult social care users_18+ yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social Isolation: percentage of adult social care users who have as much social contact as they would like_18+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_3)
```

```{r}
#Linear Regression for 'Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons'
LinReg_4 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_4)
#Plot Linear Regression for Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Adults in treatment at specialist alcohol misuse services: rate per 1000 population_18+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_4)
```

```{r}
#Linear Regression for 'Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons'
LinReg_5 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_5)
#Plot Linear Regression for Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Adults in treatment at specialist drug misuse services: rate per 1000 population_18+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_5)
```

```{r}
#Linear Regression for 'Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Female'
LinReg_6 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Female`,data=analysis_final_new)
summary(LinReg_6)
#Plot Linear Regression for Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Female 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Female`  ,data=analysis_final_new)
abline(LinReg_6)
```

```{r}
#Linear Regression for 'Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Male'
LinReg_7 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Male` ,data=analysis_final_new)
summary(LinReg_7)
#Plot Linear Regression for Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Male 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Male` ,data=analysis_final_new)
abline(LinReg_7)
```

```{r}
#Linear Regression for 'Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Persons'
LinReg_8 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Persons`,data=analysis_final_new)
summary(LinReg_8)
#Plot Linear Regression for Alcohol-related hospital admission (Broad): directly age standardised rate per 100,000 population_All ages_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Admission episodes for alcohol-related conditions (Broad): Old Method_All ages_Persons`,data=analysis_final_new)
abline(LinReg_8)
```

```{r}
#Linear Regression for 'Children in the youth justice system: rate per 1,000 aged 10 - 18_10-18 yrs_Persons'
LinReg_9 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Children in the youth justice system (10-17 yrs)_10-17 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_9)
#Plot Linear Regression for Children in the youth justice system: rate per 1,000 aged 10 - 18_10-18 yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Children in the youth justice system (10-17 yrs)_10-17 yrs_Persons`,data=analysis_final_new)
abline(LinReg_9)
```

```{r}
#Linear Regression for 'Children leaving care: rate per 10,000 <18 population_<18 yrs_Persons'
LinReg_10 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Children leaving care: rate per 10,000 children aged under 18_<18 yrs_Persons`,data=analysis_final_new)
summary(LinReg_10)
#Plot Linear Regression for Children leaving care: rate per 10,000 <18 population_<18 yrs_Persons 
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Children leaving care: rate per 10,000 children aged under 18_<18 yrs_Persons`,data=analysis_final_new)
abline(LinReg_10)
```

```{r}
#Linear Regression for 'Depression recorded prevalence (QOF): % of practice register aged 18+_18+ yrs_Persons'
LinReg_11 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Depression: Recorded prevalence (aged 18+)_18+ yrs_Persons`   ,data=analysis_final_new)
summary(LinReg_11)
#Plot Linear Regression for Depression recorded prevalence (QOF): % of practice register aged 18+_18+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Depression: Recorded prevalence (aged 18+)_18+ yrs_Persons`    ,data=analysis_final_new)
abline(LinReg_11)
```

```{r}
#Linear Regression for 'Domestic abuse incidents: rate per 1,000 population_16+ yrs_Persons'
LinReg_12 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Domestic abuse incidents: rate per 1,000 population_16+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_12)
#Plot Linear Regression for Domestic abuse incidents: rate per 1,000 population_16+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Domestic abuse incidents: rate per 1,000 population_16+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_12)
```

```{r}
#Linear Regression for 'Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Female'
LinReg_13 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Female` ,data=analysis_final_new)
summary(LinReg_13)
#Plot Linear Regression for Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Female
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Female` ,data=analysis_final_new)
abline(LinReg_13)
```

```{r}
#Linear Regression for 'Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Male'
LinReg_14 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Male` ,data=analysis_final_new)
summary(LinReg_14)
#Plot Linear Regression for Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Male
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Male` ,data=analysis_final_new)
abline(LinReg_14)
```

```{r}
#Linear Regression for 'Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Persons'
LinReg_15 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Persons` ,data=analysis_final_new)
summary(LinReg_15)
#Plot Linear Regression for Emergency Hospital Admissions for Intentional Self-Harm: Directly age-sex standardised rate per 100,000_All ages_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Emergency Hospital Admissions for Intentional Self-Harm_All ages_Persons` ,data=analysis_final_new)
abline(LinReg_15)
```

```{r}
#Linear Regression for 'Estimated prevalence of opiates and/or crack cocaine use: rate per 1,000 population aged 15 - 64_15-64 yrs_Persons'
LinReg_16 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Estimated prevalence of opiates and/or crack cocaine use: rate per 1,000 population aged 15 - 64_15-64 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_16)
#Plot Linear Regression for Estimated prevalence of opiates and/or crack cocaine use: rate per 1,000 population aged 15 - 64_15-64 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Estimated prevalence of opiates and/or crack cocaine use: rate per 1,000 population aged 15 - 64_15-64 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_16)
```

```{r}
#Linear Regression for 'Long-term health problems or disability: % of people whose day-to-day activities are limited by their health or disability_All ages_Persons'
LinReg_17 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Long-term health problems or disability: % of people whose day-to-day activities are limited by their health or disability_All ages_Persons` ,data=analysis_final_new)
summary(LinReg_17)
#Plot Linear Regression for Long-term health problems or disability: % of people whose day-to-day activities are limited by their health or disability_All ages_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Long-term health problems or disability: % of people whose day-to-day activities are limited by their health or disability_All ages_Persons` ,data=analysis_final_new)
```

```{r}
#Linear Regression for 'Long-term unemployment: % of working age population_16-64 yrs_Persons'
LinReg_18 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Long-term unemployment: % of working age population_16-64 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_18)
#Plot Linear Regression for Long-term unemployment: % of working age population_16-64 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Long-term unemployment: % of working age population_16-64 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_18)
```

```{r}
#Linear Regression for 'Looked after children: rate per 10,000 <18 population_<18 yrs_Persons'
LinReg_19 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Looked after children: rate per 10,000 <18 population_<18 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_19)
#Plot Linear Regression for Looked after children: rate per 10,000 <18 population_<18 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Looked after children: rate per 10,000 <18 population_<18 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_19)
```

```{r}
#Linear Regression for 'Marital breakup: % of adults_18+ yrs_Persons'
LinReg_20 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Marital breakup: % of adults_18+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_20)
#Plot Linear Regression for Marital breakup: % of adults_18+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Marital breakup: % of adults_18+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_20)
```

```{r}
#Linear Regression for 'Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons'
LinReg_21 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_21)
#Plot Linear Regression for Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Older people living alone: % of households occupied by a single person aged 65 or over_65+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_21)
```

```{r}
#Linear Regression for 'People living alone: % of all usual residents in households occupied by a single person_All ages_Persons'
LinReg_22 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`People living alone: % of all usual residents in households occupied by a single person_All ages_Persons` ,data=analysis_final_new)
summary(LinReg_22)
#Plot Linear Regression for People living alone: % of all usual residents in households occupied by a single person_All ages_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`People living alone: % of all usual residents in households occupied by a single person_All ages_Persons` ,data=analysis_final_new)
abline(LinReg_22)
```

```{r}
#Linear Regression for 'Self-reported well-being: % of people with a high anxiety score_16+ yrs_Persons'
LinReg_23 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Self-reported well-being: % of people with a high anxiety score_16+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_23)
#Plot Linear Regression for Self-reported well-being: % of people with a high anxiety score_16+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Self-reported well-being: % of people with a high anxiety score_16+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_23)
```

```{r}
#Linear Regression for 'Severe mental illness recorded prevalence (QOF): % of practice register (all ages)_All ages_Persons'
LinReg_24 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Severe mental illness recorded prevalence (QOF): % of practice register (all ages)_All ages_Persons` ,data=analysis_final_new)
summary(LinReg_24)
#Plot Linear Regression for Severe mental illness recorded prevalence (QOF): % of practice register (all ages)_All ages_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Severe mental illness recorded prevalence (QOF): % of practice register (all ages)_All ages_Persons` ,data=analysis_final_new)
abline(LinReg_24)
```

```{r}
#Linear Regression for 'Social care mental health clients receiving services: rate per 100,000 population_18-64 yrs_Persons'
LinReg_25 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social care mental health clients receiving services: rate per 100,000 population_18-64 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_25)
#Plot Linear Regression for Social care mental health clients receiving services: rate per 100,000 population_18-64 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Social care mental health clients receiving services: rate per 100,000 population_18-64 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_25)
```

```{r}
#Linear Regression for 'Statutory homelessness: rate per 1000 households_Not applicable_Not applicable'
LinReg_26 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Statutory homelessness: rate per 1000 households_Not applicable_Not applicable` ,data=analysis_final_new)
summary(LinReg_26)
#Plot Linear Regression for Statutory homelessness: rate per 1000 households_Not applicable_Not applicable
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Statutory homelessness: rate per 1000 households_Not applicable_Not applicable` ,data=analysis_final_new)
abline(LinReg_26)
```

```{r}
#Linear Regression for 'Successful completion of alcohol treatment:% who do not re-present to treatment within 6 months_18-75 yrs_Persons'
LinReg_27 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of alcohol treatment:% who do not re-present to treatment within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_27)
#Plot Linear Regression for Successful completion of alcohol treatment:% who do not re-present to treatment within 6 months_18-75 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of alcohol treatment:% who do not re-present to treatment within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_27)
```

```{r}
#Linear Regression for 'Successful completion of drug treatment - non-opiate users: % who do not re-present within 6 months_18-75 yrs_Persons'
LinReg_28 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of drug treatment - non-opiate users: % who do not re-present within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_28)
#Plot Linear Regression for Successful completion of drug treatment - non-opiate users: % who do not re-present within 6 months_18-75 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of drug treatment - non-opiate users: % who do not re-present within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_28)
```

```{r}
#Linear Regression for 'Successful completion of drug treatment - opiate users: % who do not re-present within 6 months_18-75 yrs_Persons'
LinReg_29 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of drug treatment - opiate users: % who do not re-present within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
summary(LinReg_29)
#Plot Linear Regression for Successful completion of drug treatment - opiate users: % who do not re-present within 6 months_18-75 yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Successful completion of drug treatment - opiate users: % who do not re-present within 6 months_18-75 yrs_Persons` ,data=analysis_final_new)
abline(LinReg_29)
```

```{r}
#Linear Regression for 'Unemployment: % of working age population_16+ yrs_Persons'
LinReg_30 <- lm(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Unemployment: % of working age population_16+ yrs_Persons` ,data=analysis_final_new)
summary(LinReg_30)
#Plot Linear Regression for Unemployment: % of working age population_16+ yrs_Persons
plot(analysis_final_new$Suicide_Rate ~ analysis_final_new$`Unemployment: % of working age population_16+ yrs_Persons` ,data=analysis_final_new)
abline(LinReg_30)
```

```{r}
#Assumption to do Factor Analysis: 
#1. Determinant of correlation matrix must be near 0
#2. KMO test > 0.5
#3. MSA every variables > 0.5 (repeat the process if there is any variables have MSA<0.5)
#4. Bartlett test -> p-value<0.05

#Create new table, exclude suicide rate
analysis_factor_new<-analysis_final_new
analysis_factor_new$Suicide_Rate<-NULL
```

```{r}
#Create correlation matrix and determinant of matrix correlation
cor_factor_new<-cor(analysis_factor_new, method = c("pearson"))
det(cor_factor_new)
#Determinant value near 0 --> correlation matrix between variable is correlated

#write.csv(cor_factor_new,file ="F:/Study/PHE/cor_factor_new.csv")
#write.csv(cor_new,file ="F:/Study/PHE/cor_new.csv")
```

```{r}
#KMO (Kaiser-Meyer-Olkin) statistic test, sampling adequacy predicts if data are likely to factor well, based on correlation and partial correlation. 
KMO(analysis_factor_new)
#KMO=0.79, could be proceed to factor analysis since KMO>0.5

#MSA (Measures of Sampling Adequacy) --> Remove variables with MSA < 0.5
#Result-> No variables has to be removed
```

```{r}
#Bartlett's test/homogenity of variances
bartlett.test(analysis_factor_new)
#Bartlett Chi-square=23985, p-Value<2.2e-16 --> significance / reject H0 --> at least one sample has a significantly difference variance
```

```{r}
#Principal Componenet Analysis (PCA) to find how many factors 
#Criteria factor, if standard deviation(eigenvalues)>1
pca1_new = princomp(analysis_factor_new, scores=TRUE, cor=TRUE)
summary(pca1_new)
#There are 7 factors which with eigenvalues > 1
#These 7 factors explains 75.35% of variables
```

```{r}
#Loading factors PCA
loadings(pca1_new)
#Notice that R uses a cut off of .1 so some loadings are blank.
```

```{r}
analysis_factor_new
```

```{r}
# Using 10 factors, since it can not use 7 factors as refferenced by PCA
fa1_new<-factanal(analysis_factor_new,factors=10, scores="regression")
```

```{r}
#Loading factors
fa1_new$loadings
```

```{r}
#Select loadings factor only
mload_new<-fa1_new$loadings
mload_new
```

```{r}
#Convert each cells to absolute number
mload_abs_new<-abs(mload_new)
mload_abs1_new<-mload_abs_new[,1:10]
mloaddf_new<-as.data.frame(mload_abs1_new)
mloaddf_new
```

```{r}
#Ordering Factor1
mload_sort_new<-mloaddf_new[order(mloaddf_new$Factor1),]
mload_sort_new
```

```{r}
#Grouping each variables to the same factors
mload_sort_new$Max<-colnames(mload_sort_new)[max.col(mload_sort_new,ties.method="first")]
mload_sort_new$Max
split(rownames(mload_sort_new),mload_sort_new[,"Max"])
```

```{r}
#Hierarchical clustering

#Table with Counties as rowname
hierclus_table<-analysis_factor_new
hierclus_table<-cbind(a = analysis1new[,1], hierclus_table)
```

```{r}
#Make first column (AreaName) as a rowname
hierclus_table<-as.data.frame(hierclus_table[,-1], row.names=hierclus_table[,1])
```

```{r}
#Standardizing data
stan_data<-scale(hierclus_table)
```

```{r}
#Dissimilarity/proximities matrix with eucidean method
dis_mat <- dist(stan_data, method = "euclidean")
```

```{r}
#Clustering
hier_clus<-hclust(dis_mat, method = "complete")
```

```{r}
# Plot the obtained dendrogram
plot(hier_clus, cex = 0.6, hang = -1)
```


