---
title: "Corss Validaton"
output: html_document
---

# I will continuously update this file.

```{r}
#Cross Validation
library(ISLR)
set.seed(1)
train = sample(392,196)
```

```{r}
lm.fit <- lm(mpg ~ horsepower , data = Auto , subset = train)
```

```{r}
#attach(Auto)
mean((mpg - predict(lm.fit,Auto))[-train]^2)
```

```{r}
lm.fit2 <- lm(mpg ~ poly(horsepower,2), data = Auto , subset = train)
mean ((mpg - predict (lm.fit2 , Auto))[-train]^2)
lm.fit3 <- lm(mpg ~ poly(horsepower , 3), data = Auto , subset = train)
mean ((mpg - predict (lm.fit3 , Auto))[-train]^2)
```

```{r}
set.seed(1)
train = sample(392,196)
lm.fit <- lm(mpg ~ horsepower , data = Auto , subset = train)
mean((mpg - predict(lm.fit,Auto))[-train]^2)
lm.fit2 <- lm(mpg ~ poly(horsepower,2), data = Auto , subset = train)
mean ((mpg - predict (lm.fit2 , Auto))[-train]^2)
lm.fit3 <- lm(mpg ~ poly(horsepower , 3), data = Auto , subset = train)
mean ((mpg - predict (lm.fit3 , Auto))[-train]^2)
```

```{r}

```

