---
title: "Survival Analysis"
output: html_document
---

# I will continuously update this file.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1)
```{r}
library(ISLR2)
names(BrainCancer)
```

```{r}
attach(BrainCancer)
table(sex)
table(diagnosis)
table(status)
```

```{r}
library(survival)
fit.surv <- survfit(Surv(time,status)~1)
plot(fit.surv, xlab = "Months", ylab = "Estimated Probability of Survival")
```

```{r}
fit.sex <- survfit(Surv(time, status) ~ sex)
plot(fit.sex, xlab = " Months ", ylab = "Estimated Probability of Survival", col = c(2,4))
legend ("bottomleft", levels(sex), col = c(2,4), lty = 1)
```

```{r}
logrank.test <- survdiff(Surv(time, status) ~ sex)
logrank.test
```

```{r}
fit.cox <- coxph(Surv(time, status) ~ sex)
summary(fit.cox)
```

```{r}
summary(fit.cox)$logtest[1]
summary(fit.cox)$waldtest[1]
summary(fit.cox)$sctest[1]
logrank.test$chisq
```

```{r}
fit.all <- coxph(Surv(time, status) ~ sex + diagnosis + loc + ki + gtv + stereo)
fit.all
```

```{r}
modaldata <- data.frame(
diagnosis = levels(diagnosis),
sex = rep("Female", 4),
loc = rep("Supratentorial", 4),
ki = rep(mean(ki), 4),
gtv = rep( mean (gtv), 4),
stereo = rep("SRT", 4)
)
survplots <- survfit(fit.all, newdata = modaldata)
plot(survplots, xlab = " Months ", ylab = " Survival Probability ", col = 2:5)
legend("bottomleft", levels(diagnosis), col = 2:5, lty = 1)
```

```{r}
fit.posres <- survfit(Surv (time, status) ~ posres , data = Publication)
plot(fit.posres, xlab = "Months", ylab = "Probability of Not Being Published", col = 3:4)
legend("topright", c("Negative Result", "Positive Result"),col = 3:4, lty = 1)
```

```{r}
fit.pub <- coxph(Surv(time, status) ~ posres, data = Publication)
fit.pub
```

```{r}
logrank.test <- survdiff(Surv(time, status) ~ posres, data = Publication)
logrank.test
```

```{r}
fit.pub2 <- coxph(Surv(time, status) ~ . - mech, data = Publication)
fit.pub2
```

```{r}
set.seed(4)
N <- 2000
Operators <- sample (5:15, N, replace = T)
Center <- sample (c("A", "B", "C"), N, replace = T)
Time <- sample (c(" Morn .", " After .", " Even ."), N, replace = T)
X <- model.matrix ( ~ Operators + Center + Time)[, -1]
```

